# Generated by Django 4.1.5 on 2024-02-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_range", models.CharField(max_length=255)),
                ("product_group", models.CharField(max_length=255)),
                ("style", models.CharField(max_length=255)),
                ("item_code", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
